/**
 * filehostingservice
 * File Hosting Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<File, \'id\'>, schemaOptions: { title: \'NewFile\', exclude: [ \'id\' ] })
 */
export interface NewFile { 
    name: string;
    size?: number;
    creationDate?: number;
    userId?: string;
}

